AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Style/Documentation:
  Enabled: false


Metrics/BlockLength:
  Exclude:
    - spec/**/*
